### ISSUE TITLE
No man page for compile_et(1)

### ISSUE THREAD

**Issue by abhinav-upadhyay** [heimdal/heimdal#178]
Hi,

Several man pages have reference to compile_et(1), while there is no such man page in heimdal. Could you please provide a man page for compile_et(1)?

Or otherwise if the references to compile_et(1) are to be removed, I could send a patch for that :)

**Comment by nicowilliams** [comment]
I believe this should fix it:

    diff --git a/lib/com_err/Makefile.am b/lib/com_err/Makefile.am
    index a970b64..e5b51b0 100644
    --- a/lib/com_err/Makefile.am
    +++ b/lib/com_err/Makefile.am
    @@ -13,7 +13,7 @@ endif

     libcom_err_la_LIBADD = $(LIB_libintl)

    -bin_PROGRAMS = compile_et
    +noinst_PROGRAMS = compile_et

     include_HEADERS = com_err.h com_right.h


I'll test this in a bit.

**Comment by abhinav-upadhyay** [comment]
Thanks for doing this. But the issue still remains, there are a lot of man pages which reference compile_et, even though it is no more installed, the references still remain. Should those references be removed from other man pages?

**Comment by lhoward** [comment]
Is there a reason this is not installed? This breaks building Moonshot against Heimdal.
